### ISSUE TITLE
Just a note on installation

### ISSUE THREAD

**Issue by hpanago** [kroustou/talk_python_to_me_offline#1]
After the git clone, in order for the 'python dowload.py' to work one should do a 'sudo pip install bs4' first.
At least with python 2.7 on Ubuntu.

**Comment by kroustou** [comment]
Thanks. Resolved in c0a3ae6e1c4c7dd3d7137653dd5291f9add4bbd1 which adds a requirements.txt file in order to install dependencies with pip
